### ISSUE TITLE
Add a way to reconnect a player to the server they were playing on

### ISSUE THREAD

**Issue by NyaomiDEV** [4drian3d/KickRedirect#93] opened 2024-08-26 06:21 UTC
If a kick happens because a server is restarting, it would be nice to have KickRedirect attempt reconnection. This could be achieved by simply parsing the kick message, understanding that the player is supposed to "go back", and send them back once the server is reachable again (eg. it doesn't kick the player anymore for "starting" "preparing" "connection timeout" reasons).

**Comment by 4drian3d** [comment] 2024-11-11 00:03
duplicate of #94 _(technically it is the other way around, but ¯\\_(ツ)_\/¯)_

**Closed by 4drian3d** 2024-11-11 00:03 UTC
